"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem install-cross-package-gate`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'socialia' references
in its source tree. Three outcomes:

- Module installed AND import succeeds -> test PASSES.
- Module installed BUT the submodule was renamed (e.g.
  `scitex_io._load_cache` -> `scitex_io._loading._load_cache`) ->
  test FAILS loudly.
- Peer standalone NOT installed at all (lean/CI env without the optional
  extra) -> test is SKIPPED.

HOW THE THREE OUTCOMES ARE KEPT DISTINGUISHABLE — read before editing.

The skip is scoped to the ROOT package, and the FULL dotted path is then
hard-imported:

    pytest.importorskip(root)            # peer genuinely absent -> SKIP
    importlib.import_module(target)      # submodule renamed     -> FAIL

Calling `pytest.importorskip(module_name)` on the FULL path instead — which
is what this gate did until PS-140 caught it — collapses the middle case
into the last one. A renamed submodule raises `ModuleNotFoundError`, an
`ImportError` subclass, so `importorskip` SKIPS it and the run reports
green: the one failure this gate exists to catch was the one failure it
could not report.

The opposite pole is equally wrong, so do NOT simply drop the skip: a
blanket hard import turns a legitimate absence (optional extra, marker-gated
dependency) into a hard failure — a gate that cannot PASS in place of one
that cannot FAIL. The rule is about SCOPE, not about the function.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_dev",
    "scitex_dev._branding",
    "scitex_dev._cli._completion",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing socialia's declared cross-package dependency must succeed."""
    # Arrange
    target = module_name
    root = target.split(".")[0]
    # Act
    pytest.importorskip(root)
    module = importlib.import_module(target)
    # Assert
    assert module.__name__ == target
