"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil
from pathlib import Path

import pytest

if shutil.which("scitex-dev") is None:
    pytest.skip(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]",
        allow_module_level=True,
    )


def test_audit_all_clean_for_socialia_package():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    gate = Path(__file__).resolve().parents[2]
    # Act
    outcome = audit_all_for_package("socialia", path=gate)
    # Assert
    assert outcome is None
